# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - windows
    - linux
  goarch:
    - amd64
  dir: provider
  main: ./cmd/pulumi-resource-rke/
  ldflags: -X github.com/jaxxstorm/pulumi-rke/provider/pkg/version.Version={{.Version}}
  binary: pulumi-resource-rke
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
archives:
  - name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files: [] # Empty

