// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Cluster extends pulumi.CustomResource {
    /**
     * Get an existing Cluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClusterState, opts?: pulumi.CustomResourceOptions): Cluster {
        return new Cluster(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'rke:index/cluster:Cluster';

    /**
     * Returns true if the given object is an instance of Cluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Cluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Cluster.__pulumiType;
    }

    /**
     * RKE k8s cluster addon deployment timeout in seconds for status check
     */
    public readonly addonJobTimeout!: pulumi.Output<number>;
    /**
     * RKE k8s cluster user addons YAML manifest to be deployed
     */
    public readonly addons!: pulumi.Output<string | undefined>;
    /**
     * RKE k8s cluster user addons YAML manifest urls or paths to be deployed
     */
    public readonly addonsIncludes!: pulumi.Output<string[] | undefined>;
    /**
     * RKE k8s cluster api server url
     */
    public /*out*/ readonly apiServerUrl!: pulumi.Output<string>;
    /**
     * RKE k8s cluster authentication configuration
     */
    public readonly authentication!: pulumi.Output<outputs.ClusterAuthentication>;
    /**
     * RKE k8s cluster authorization mode configuration
     */
    public readonly authorization!: pulumi.Output<outputs.ClusterAuthorization>;
    /**
     * RKE k8s cluster bastion Host configuration
     */
    public readonly bastionHost!: pulumi.Output<outputs.ClusterBastionHost | undefined>;
    /**
     * RKE k8s cluster CA certificate
     */
    public /*out*/ readonly caCrt!: pulumi.Output<string>;
    /**
     * Specify a certificate dir path
     */
    public readonly certDir!: pulumi.Output<string | undefined>;
    /**
     * RKE k8s cluster certificates
     */
    public /*out*/ readonly certificates!: pulumi.Output<outputs.ClusterCertificate[]>;
    /**
     * RKE k8s cluster client certificate
     */
    public /*out*/ readonly clientCert!: pulumi.Output<string>;
    /**
     * RKE k8s cluster client key
     */
    public /*out*/ readonly clientKey!: pulumi.Output<string>;
    /**
     * RKE k8s cluster cloud provider configuration
     */
    public readonly cloudProvider!: pulumi.Output<outputs.ClusterCloudProvider | undefined>;
    /**
     * RKE k8s cluster cidr
     */
    public /*out*/ readonly clusterCidr!: pulumi.Output<string>;
    /**
     * RKE k8s cluster dns server
     */
    public /*out*/ readonly clusterDnsServer!: pulumi.Output<string>;
    /**
     * RKE k8s cluster domain
     */
    public /*out*/ readonly clusterDomain!: pulumi.Output<string>;
    /**
     * RKE k8s cluster name used in the kube config
     */
    public readonly clusterName!: pulumi.Output<string>;
    /**
     * RKE k8s cluster config yaml
     */
    public readonly clusterYaml!: pulumi.Output<string | undefined>;
    /**
     * RKE k8s cluster control plane nodes
     */
    public /*out*/ readonly controlPlaneHosts!: pulumi.Output<outputs.ClusterControlPlaneHost[]>;
    /**
     * Use custom certificates from a cert dir
     */
    public readonly customCerts!: pulumi.Output<boolean | undefined>;
    /**
     * RKE k8s cluster delay on creation
     */
    public readonly delayOnCreation!: pulumi.Output<number | undefined>;
    /**
     * RKE k8s cluster dind (experimental)
     */
    public readonly dind!: pulumi.Output<boolean | undefined>;
    /**
     * RKE k8s cluster dind storage driver (experimental)
     */
    public readonly dindDnsServer!: pulumi.Output<string | undefined>;
    /**
     * RKE k8s cluster dind storage driver (experimental)
     */
    public readonly dindStorageDriver!: pulumi.Output<string | undefined>;
    /**
     * Enable/Disable RKE k8s cluster port checking
     */
    public readonly disablePortCheck!: pulumi.Output<boolean | undefined>;
    /**
     * RKE k8s cluster DNS Config
     */
    public readonly dns!: pulumi.Output<outputs.ClusterDns>;
    /**
     * RKE k8s cluster etcd nodes
     */
    public /*out*/ readonly etcdHosts!: pulumi.Output<outputs.ClusterEtcdHost[]>;
    /**
     * Enable/Disable RKE k8s cluster strict docker version checking
     */
    public readonly ignoreDockerVersion!: pulumi.Output<boolean>;
    /**
     * RKE k8s cluster inactive nodes
     */
    public /*out*/ readonly inactiveHosts!: pulumi.Output<outputs.ClusterInactiveHost[]>;
    /**
     * RKE k8s cluster ingress controller configuration
     */
    public readonly ingress!: pulumi.Output<outputs.ClusterIngress>;
    public /*out*/ readonly internalKubeConfigYaml!: pulumi.Output<string>;
    /**
     * RKE k8s cluster admin user
     */
    public /*out*/ readonly kubeAdminUser!: pulumi.Output<string>;
    /**
     * RKE k8s cluster kube config yaml
     */
    public /*out*/ readonly kubeConfigYaml!: pulumi.Output<string>;
    /**
     * K8s version to deploy (if kubernetes image is specified, image version takes precedence)
     */
    public readonly kubernetesVersion!: pulumi.Output<string | undefined>;
    /**
     * RKE k8s cluster monitoring Config
     */
    public readonly monitoring!: pulumi.Output<outputs.ClusterMonitoring>;
    /**
     * RKE k8s cluster network configuration
     */
    public readonly network!: pulumi.Output<outputs.ClusterNetwork>;
    /**
     * RKE k8s cluster nodes
     */
    public readonly nodes!: pulumi.Output<outputs.ClusterNode[] | undefined>;
    public readonly nodesConfs!: pulumi.Output<string[] | undefined>;
    /**
     * RKE k8s directory path
     */
    public readonly prefixPath!: pulumi.Output<string>;
    /**
     * RKE k8s cluster private docker registries
     */
    public readonly privateRegistries!: pulumi.Output<outputs.ClusterPrivateRegistry[] | undefined>;
    /**
     * RKE k8s cluster restore configuration
     */
    public readonly restore!: pulumi.Output<outputs.ClusterRestore>;
    /**
     * RKE k8s cluster config yaml
     */
    public /*out*/ readonly rkeClusterYaml!: pulumi.Output<string>;
    /**
     * RKE k8s cluster state
     */
    public /*out*/ readonly rkeState!: pulumi.Output<string>;
    /**
     * RKE k8s cluster rotate certificates configuration
     */
    public readonly rotateCertificates!: pulumi.Output<outputs.ClusterRotateCertificates | undefined>;
    /**
     * RKE k8s cluster running system images list
     */
    public /*out*/ readonly runningSystemImages!: pulumi.Output<outputs.ClusterRunningSystemImages>;
    /**
     * RKE k8s cluster services
     */
    public readonly services!: pulumi.Output<outputs.ClusterServices>;
    public readonly servicesEtcdDeprecated!: pulumi.Output<outputs.ClusterServicesEtcdDeprecated | undefined>;
    public readonly servicesKubeApiDeprecated!: pulumi.Output<outputs.ClusterServicesKubeApiDeprecated | undefined>;
    public readonly servicesKubeControllerDeprecated!: pulumi.Output<outputs.ClusterServicesKubeControllerDeprecated | undefined>;
    public readonly servicesKubeletDeprecated!: pulumi.Output<outputs.ClusterServicesKubeletDeprecated | undefined>;
    public readonly servicesKubeProxyDeprecated!: pulumi.Output<outputs.ClusterServicesKubeProxyDeprecated | undefined>;
    public readonly servicesKubeSchedulerDeprecated!: pulumi.Output<outputs.ClusterServicesKubeSchedulerDeprecated | undefined>;
    /**
     * SSH Agent Auth enable
     */
    public readonly sshAgentAuth!: pulumi.Output<boolean>;
    /**
     * SSH Certificate Path
     */
    public readonly sshCertPath!: pulumi.Output<string>;
    /**
     * SSH Private Key Path
     */
    public readonly sshKeyPath!: pulumi.Output<string>;
    /**
     * RKE k8s cluster system images list
     */
    public readonly systemImages!: pulumi.Output<outputs.ClusterSystemImages | undefined>;
    /**
     * Skip idempotent deployment of control and etcd plane
     */
    public readonly updateOnly!: pulumi.Output<boolean | undefined>;
    /**
     * RKE k8s cluster upgrade strategy
     */
    public readonly upgradeStrategy!: pulumi.Output<outputs.ClusterUpgradeStrategy | undefined>;
    /**
     * RKE k8s cluster worker nodes
     */
    public /*out*/ readonly workerHosts!: pulumi.Output<outputs.ClusterWorkerHost[]>;

    /**
     * Create a Cluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ClusterArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClusterArgs | ClusterState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as ClusterState | undefined;
            inputs["addonJobTimeout"] = state ? state.addonJobTimeout : undefined;
            inputs["addons"] = state ? state.addons : undefined;
            inputs["addonsIncludes"] = state ? state.addonsIncludes : undefined;
            inputs["apiServerUrl"] = state ? state.apiServerUrl : undefined;
            inputs["authentication"] = state ? state.authentication : undefined;
            inputs["authorization"] = state ? state.authorization : undefined;
            inputs["bastionHost"] = state ? state.bastionHost : undefined;
            inputs["caCrt"] = state ? state.caCrt : undefined;
            inputs["certDir"] = state ? state.certDir : undefined;
            inputs["certificates"] = state ? state.certificates : undefined;
            inputs["clientCert"] = state ? state.clientCert : undefined;
            inputs["clientKey"] = state ? state.clientKey : undefined;
            inputs["cloudProvider"] = state ? state.cloudProvider : undefined;
            inputs["clusterCidr"] = state ? state.clusterCidr : undefined;
            inputs["clusterDnsServer"] = state ? state.clusterDnsServer : undefined;
            inputs["clusterDomain"] = state ? state.clusterDomain : undefined;
            inputs["clusterName"] = state ? state.clusterName : undefined;
            inputs["clusterYaml"] = state ? state.clusterYaml : undefined;
            inputs["controlPlaneHosts"] = state ? state.controlPlaneHosts : undefined;
            inputs["customCerts"] = state ? state.customCerts : undefined;
            inputs["delayOnCreation"] = state ? state.delayOnCreation : undefined;
            inputs["dind"] = state ? state.dind : undefined;
            inputs["dindDnsServer"] = state ? state.dindDnsServer : undefined;
            inputs["dindStorageDriver"] = state ? state.dindStorageDriver : undefined;
            inputs["disablePortCheck"] = state ? state.disablePortCheck : undefined;
            inputs["dns"] = state ? state.dns : undefined;
            inputs["etcdHosts"] = state ? state.etcdHosts : undefined;
            inputs["ignoreDockerVersion"] = state ? state.ignoreDockerVersion : undefined;
            inputs["inactiveHosts"] = state ? state.inactiveHosts : undefined;
            inputs["ingress"] = state ? state.ingress : undefined;
            inputs["internalKubeConfigYaml"] = state ? state.internalKubeConfigYaml : undefined;
            inputs["kubeAdminUser"] = state ? state.kubeAdminUser : undefined;
            inputs["kubeConfigYaml"] = state ? state.kubeConfigYaml : undefined;
            inputs["kubernetesVersion"] = state ? state.kubernetesVersion : undefined;
            inputs["monitoring"] = state ? state.monitoring : undefined;
            inputs["network"] = state ? state.network : undefined;
            inputs["nodes"] = state ? state.nodes : undefined;
            inputs["nodesConfs"] = state ? state.nodesConfs : undefined;
            inputs["prefixPath"] = state ? state.prefixPath : undefined;
            inputs["privateRegistries"] = state ? state.privateRegistries : undefined;
            inputs["restore"] = state ? state.restore : undefined;
            inputs["rkeClusterYaml"] = state ? state.rkeClusterYaml : undefined;
            inputs["rkeState"] = state ? state.rkeState : undefined;
            inputs["rotateCertificates"] = state ? state.rotateCertificates : undefined;
            inputs["runningSystemImages"] = state ? state.runningSystemImages : undefined;
            inputs["services"] = state ? state.services : undefined;
            inputs["servicesEtcdDeprecated"] = state ? state.servicesEtcdDeprecated : undefined;
            inputs["servicesKubeApiDeprecated"] = state ? state.servicesKubeApiDeprecated : undefined;
            inputs["servicesKubeControllerDeprecated"] = state ? state.servicesKubeControllerDeprecated : undefined;
            inputs["servicesKubeletDeprecated"] = state ? state.servicesKubeletDeprecated : undefined;
            inputs["servicesKubeProxyDeprecated"] = state ? state.servicesKubeProxyDeprecated : undefined;
            inputs["servicesKubeSchedulerDeprecated"] = state ? state.servicesKubeSchedulerDeprecated : undefined;
            inputs["sshAgentAuth"] = state ? state.sshAgentAuth : undefined;
            inputs["sshCertPath"] = state ? state.sshCertPath : undefined;
            inputs["sshKeyPath"] = state ? state.sshKeyPath : undefined;
            inputs["systemImages"] = state ? state.systemImages : undefined;
            inputs["updateOnly"] = state ? state.updateOnly : undefined;
            inputs["upgradeStrategy"] = state ? state.upgradeStrategy : undefined;
            inputs["workerHosts"] = state ? state.workerHosts : undefined;
        } else {
            const args = argsOrState as ClusterArgs | undefined;
            inputs["addonJobTimeout"] = args ? args.addonJobTimeout : undefined;
            inputs["addons"] = args ? args.addons : undefined;
            inputs["addonsIncludes"] = args ? args.addonsIncludes : undefined;
            inputs["authentication"] = args ? args.authentication : undefined;
            inputs["authorization"] = args ? args.authorization : undefined;
            inputs["bastionHost"] = args ? args.bastionHost : undefined;
            inputs["certDir"] = args ? args.certDir : undefined;
            inputs["cloudProvider"] = args ? args.cloudProvider : undefined;
            inputs["clusterName"] = args ? args.clusterName : undefined;
            inputs["clusterYaml"] = args ? args.clusterYaml : undefined;
            inputs["customCerts"] = args ? args.customCerts : undefined;
            inputs["delayOnCreation"] = args ? args.delayOnCreation : undefined;
            inputs["dind"] = args ? args.dind : undefined;
            inputs["dindDnsServer"] = args ? args.dindDnsServer : undefined;
            inputs["dindStorageDriver"] = args ? args.dindStorageDriver : undefined;
            inputs["disablePortCheck"] = args ? args.disablePortCheck : undefined;
            inputs["dns"] = args ? args.dns : undefined;
            inputs["ignoreDockerVersion"] = args ? args.ignoreDockerVersion : undefined;
            inputs["ingress"] = args ? args.ingress : undefined;
            inputs["kubernetesVersion"] = args ? args.kubernetesVersion : undefined;
            inputs["monitoring"] = args ? args.monitoring : undefined;
            inputs["network"] = args ? args.network : undefined;
            inputs["nodes"] = args ? args.nodes : undefined;
            inputs["nodesConfs"] = args ? args.nodesConfs : undefined;
            inputs["prefixPath"] = args ? args.prefixPath : undefined;
            inputs["privateRegistries"] = args ? args.privateRegistries : undefined;
            inputs["restore"] = args ? args.restore : undefined;
            inputs["rotateCertificates"] = args ? args.rotateCertificates : undefined;
            inputs["services"] = args ? args.services : undefined;
            inputs["servicesEtcdDeprecated"] = args ? args.servicesEtcdDeprecated : undefined;
            inputs["servicesKubeApiDeprecated"] = args ? args.servicesKubeApiDeprecated : undefined;
            inputs["servicesKubeControllerDeprecated"] = args ? args.servicesKubeControllerDeprecated : undefined;
            inputs["servicesKubeletDeprecated"] = args ? args.servicesKubeletDeprecated : undefined;
            inputs["servicesKubeProxyDeprecated"] = args ? args.servicesKubeProxyDeprecated : undefined;
            inputs["servicesKubeSchedulerDeprecated"] = args ? args.servicesKubeSchedulerDeprecated : undefined;
            inputs["sshAgentAuth"] = args ? args.sshAgentAuth : undefined;
            inputs["sshCertPath"] = args ? args.sshCertPath : undefined;
            inputs["sshKeyPath"] = args ? args.sshKeyPath : undefined;
            inputs["systemImages"] = args ? args.systemImages : undefined;
            inputs["updateOnly"] = args ? args.updateOnly : undefined;
            inputs["upgradeStrategy"] = args ? args.upgradeStrategy : undefined;
            inputs["apiServerUrl"] = undefined /*out*/;
            inputs["caCrt"] = undefined /*out*/;
            inputs["certificates"] = undefined /*out*/;
            inputs["clientCert"] = undefined /*out*/;
            inputs["clientKey"] = undefined /*out*/;
            inputs["clusterCidr"] = undefined /*out*/;
            inputs["clusterDnsServer"] = undefined /*out*/;
            inputs["clusterDomain"] = undefined /*out*/;
            inputs["controlPlaneHosts"] = undefined /*out*/;
            inputs["etcdHosts"] = undefined /*out*/;
            inputs["inactiveHosts"] = undefined /*out*/;
            inputs["internalKubeConfigYaml"] = undefined /*out*/;
            inputs["kubeAdminUser"] = undefined /*out*/;
            inputs["kubeConfigYaml"] = undefined /*out*/;
            inputs["rkeClusterYaml"] = undefined /*out*/;
            inputs["rkeState"] = undefined /*out*/;
            inputs["runningSystemImages"] = undefined /*out*/;
            inputs["workerHosts"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Cluster.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Cluster resources.
 */
export interface ClusterState {
    /**
     * RKE k8s cluster addon deployment timeout in seconds for status check
     */
    readonly addonJobTimeout?: pulumi.Input<number>;
    /**
     * RKE k8s cluster user addons YAML manifest to be deployed
     */
    readonly addons?: pulumi.Input<string>;
    /**
     * RKE k8s cluster user addons YAML manifest urls or paths to be deployed
     */
    readonly addonsIncludes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * RKE k8s cluster api server url
     */
    readonly apiServerUrl?: pulumi.Input<string>;
    /**
     * RKE k8s cluster authentication configuration
     */
    readonly authentication?: pulumi.Input<inputs.ClusterAuthentication>;
    /**
     * RKE k8s cluster authorization mode configuration
     */
    readonly authorization?: pulumi.Input<inputs.ClusterAuthorization>;
    /**
     * RKE k8s cluster bastion Host configuration
     */
    readonly bastionHost?: pulumi.Input<inputs.ClusterBastionHost>;
    /**
     * RKE k8s cluster CA certificate
     */
    readonly caCrt?: pulumi.Input<string>;
    /**
     * Specify a certificate dir path
     */
    readonly certDir?: pulumi.Input<string>;
    /**
     * RKE k8s cluster certificates
     */
    readonly certificates?: pulumi.Input<pulumi.Input<inputs.ClusterCertificate>[]>;
    /**
     * RKE k8s cluster client certificate
     */
    readonly clientCert?: pulumi.Input<string>;
    /**
     * RKE k8s cluster client key
     */
    readonly clientKey?: pulumi.Input<string>;
    /**
     * RKE k8s cluster cloud provider configuration
     */
    readonly cloudProvider?: pulumi.Input<inputs.ClusterCloudProvider>;
    /**
     * RKE k8s cluster cidr
     */
    readonly clusterCidr?: pulumi.Input<string>;
    /**
     * RKE k8s cluster dns server
     */
    readonly clusterDnsServer?: pulumi.Input<string>;
    /**
     * RKE k8s cluster domain
     */
    readonly clusterDomain?: pulumi.Input<string>;
    /**
     * RKE k8s cluster name used in the kube config
     */
    readonly clusterName?: pulumi.Input<string>;
    /**
     * RKE k8s cluster config yaml
     */
    readonly clusterYaml?: pulumi.Input<string>;
    /**
     * RKE k8s cluster control plane nodes
     */
    readonly controlPlaneHosts?: pulumi.Input<pulumi.Input<inputs.ClusterControlPlaneHost>[]>;
    /**
     * Use custom certificates from a cert dir
     */
    readonly customCerts?: pulumi.Input<boolean>;
    /**
     * RKE k8s cluster delay on creation
     */
    readonly delayOnCreation?: pulumi.Input<number>;
    /**
     * RKE k8s cluster dind (experimental)
     */
    readonly dind?: pulumi.Input<boolean>;
    /**
     * RKE k8s cluster dind storage driver (experimental)
     */
    readonly dindDnsServer?: pulumi.Input<string>;
    /**
     * RKE k8s cluster dind storage driver (experimental)
     */
    readonly dindStorageDriver?: pulumi.Input<string>;
    /**
     * Enable/Disable RKE k8s cluster port checking
     */
    readonly disablePortCheck?: pulumi.Input<boolean>;
    /**
     * RKE k8s cluster DNS Config
     */
    readonly dns?: pulumi.Input<inputs.ClusterDns>;
    /**
     * RKE k8s cluster etcd nodes
     */
    readonly etcdHosts?: pulumi.Input<pulumi.Input<inputs.ClusterEtcdHost>[]>;
    /**
     * Enable/Disable RKE k8s cluster strict docker version checking
     */
    readonly ignoreDockerVersion?: pulumi.Input<boolean>;
    /**
     * RKE k8s cluster inactive nodes
     */
    readonly inactiveHosts?: pulumi.Input<pulumi.Input<inputs.ClusterInactiveHost>[]>;
    /**
     * RKE k8s cluster ingress controller configuration
     */
    readonly ingress?: pulumi.Input<inputs.ClusterIngress>;
    readonly internalKubeConfigYaml?: pulumi.Input<string>;
    /**
     * RKE k8s cluster admin user
     */
    readonly kubeAdminUser?: pulumi.Input<string>;
    /**
     * RKE k8s cluster kube config yaml
     */
    readonly kubeConfigYaml?: pulumi.Input<string>;
    /**
     * K8s version to deploy (if kubernetes image is specified, image version takes precedence)
     */
    readonly kubernetesVersion?: pulumi.Input<string>;
    /**
     * RKE k8s cluster monitoring Config
     */
    readonly monitoring?: pulumi.Input<inputs.ClusterMonitoring>;
    /**
     * RKE k8s cluster network configuration
     */
    readonly network?: pulumi.Input<inputs.ClusterNetwork>;
    /**
     * RKE k8s cluster nodes
     */
    readonly nodes?: pulumi.Input<pulumi.Input<inputs.ClusterNode>[]>;
    readonly nodesConfs?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * RKE k8s directory path
     */
    readonly prefixPath?: pulumi.Input<string>;
    /**
     * RKE k8s cluster private docker registries
     */
    readonly privateRegistries?: pulumi.Input<pulumi.Input<inputs.ClusterPrivateRegistry>[]>;
    /**
     * RKE k8s cluster restore configuration
     */
    readonly restore?: pulumi.Input<inputs.ClusterRestore>;
    /**
     * RKE k8s cluster config yaml
     */
    readonly rkeClusterYaml?: pulumi.Input<string>;
    /**
     * RKE k8s cluster state
     */
    readonly rkeState?: pulumi.Input<string>;
    /**
     * RKE k8s cluster rotate certificates configuration
     */
    readonly rotateCertificates?: pulumi.Input<inputs.ClusterRotateCertificates>;
    /**
     * RKE k8s cluster running system images list
     */
    readonly runningSystemImages?: pulumi.Input<inputs.ClusterRunningSystemImages>;
    /**
     * RKE k8s cluster services
     */
    readonly services?: pulumi.Input<inputs.ClusterServices>;
    readonly servicesEtcdDeprecated?: pulumi.Input<inputs.ClusterServicesEtcdDeprecated>;
    readonly servicesKubeApiDeprecated?: pulumi.Input<inputs.ClusterServicesKubeApiDeprecated>;
    readonly servicesKubeControllerDeprecated?: pulumi.Input<inputs.ClusterServicesKubeControllerDeprecated>;
    readonly servicesKubeletDeprecated?: pulumi.Input<inputs.ClusterServicesKubeletDeprecated>;
    readonly servicesKubeProxyDeprecated?: pulumi.Input<inputs.ClusterServicesKubeProxyDeprecated>;
    readonly servicesKubeSchedulerDeprecated?: pulumi.Input<inputs.ClusterServicesKubeSchedulerDeprecated>;
    /**
     * SSH Agent Auth enable
     */
    readonly sshAgentAuth?: pulumi.Input<boolean>;
    /**
     * SSH Certificate Path
     */
    readonly sshCertPath?: pulumi.Input<string>;
    /**
     * SSH Private Key Path
     */
    readonly sshKeyPath?: pulumi.Input<string>;
    /**
     * RKE k8s cluster system images list
     */
    readonly systemImages?: pulumi.Input<inputs.ClusterSystemImages>;
    /**
     * Skip idempotent deployment of control and etcd plane
     */
    readonly updateOnly?: pulumi.Input<boolean>;
    /**
     * RKE k8s cluster upgrade strategy
     */
    readonly upgradeStrategy?: pulumi.Input<inputs.ClusterUpgradeStrategy>;
    /**
     * RKE k8s cluster worker nodes
     */
    readonly workerHosts?: pulumi.Input<pulumi.Input<inputs.ClusterWorkerHost>[]>;
}

/**
 * The set of arguments for constructing a Cluster resource.
 */
export interface ClusterArgs {
    /**
     * RKE k8s cluster addon deployment timeout in seconds for status check
     */
    readonly addonJobTimeout?: pulumi.Input<number>;
    /**
     * RKE k8s cluster user addons YAML manifest to be deployed
     */
    readonly addons?: pulumi.Input<string>;
    /**
     * RKE k8s cluster user addons YAML manifest urls or paths to be deployed
     */
    readonly addonsIncludes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * RKE k8s cluster authentication configuration
     */
    readonly authentication?: pulumi.Input<inputs.ClusterAuthentication>;
    /**
     * RKE k8s cluster authorization mode configuration
     */
    readonly authorization?: pulumi.Input<inputs.ClusterAuthorization>;
    /**
     * RKE k8s cluster bastion Host configuration
     */
    readonly bastionHost?: pulumi.Input<inputs.ClusterBastionHost>;
    /**
     * Specify a certificate dir path
     */
    readonly certDir?: pulumi.Input<string>;
    /**
     * RKE k8s cluster cloud provider configuration
     */
    readonly cloudProvider?: pulumi.Input<inputs.ClusterCloudProvider>;
    /**
     * RKE k8s cluster name used in the kube config
     */
    readonly clusterName?: pulumi.Input<string>;
    /**
     * RKE k8s cluster config yaml
     */
    readonly clusterYaml?: pulumi.Input<string>;
    /**
     * Use custom certificates from a cert dir
     */
    readonly customCerts?: pulumi.Input<boolean>;
    /**
     * RKE k8s cluster delay on creation
     */
    readonly delayOnCreation?: pulumi.Input<number>;
    /**
     * RKE k8s cluster dind (experimental)
     */
    readonly dind?: pulumi.Input<boolean>;
    /**
     * RKE k8s cluster dind storage driver (experimental)
     */
    readonly dindDnsServer?: pulumi.Input<string>;
    /**
     * RKE k8s cluster dind storage driver (experimental)
     */
    readonly dindStorageDriver?: pulumi.Input<string>;
    /**
     * Enable/Disable RKE k8s cluster port checking
     */
    readonly disablePortCheck?: pulumi.Input<boolean>;
    /**
     * RKE k8s cluster DNS Config
     */
    readonly dns?: pulumi.Input<inputs.ClusterDns>;
    /**
     * Enable/Disable RKE k8s cluster strict docker version checking
     */
    readonly ignoreDockerVersion?: pulumi.Input<boolean>;
    /**
     * RKE k8s cluster ingress controller configuration
     */
    readonly ingress?: pulumi.Input<inputs.ClusterIngress>;
    /**
     * K8s version to deploy (if kubernetes image is specified, image version takes precedence)
     */
    readonly kubernetesVersion?: pulumi.Input<string>;
    /**
     * RKE k8s cluster monitoring Config
     */
    readonly monitoring?: pulumi.Input<inputs.ClusterMonitoring>;
    /**
     * RKE k8s cluster network configuration
     */
    readonly network?: pulumi.Input<inputs.ClusterNetwork>;
    /**
     * RKE k8s cluster nodes
     */
    readonly nodes?: pulumi.Input<pulumi.Input<inputs.ClusterNode>[]>;
    readonly nodesConfs?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * RKE k8s directory path
     */
    readonly prefixPath?: pulumi.Input<string>;
    /**
     * RKE k8s cluster private docker registries
     */
    readonly privateRegistries?: pulumi.Input<pulumi.Input<inputs.ClusterPrivateRegistry>[]>;
    /**
     * RKE k8s cluster restore configuration
     */
    readonly restore?: pulumi.Input<inputs.ClusterRestore>;
    /**
     * RKE k8s cluster rotate certificates configuration
     */
    readonly rotateCertificates?: pulumi.Input<inputs.ClusterRotateCertificates>;
    /**
     * RKE k8s cluster services
     */
    readonly services?: pulumi.Input<inputs.ClusterServices>;
    readonly servicesEtcdDeprecated?: pulumi.Input<inputs.ClusterServicesEtcdDeprecated>;
    readonly servicesKubeApiDeprecated?: pulumi.Input<inputs.ClusterServicesKubeApiDeprecated>;
    readonly servicesKubeControllerDeprecated?: pulumi.Input<inputs.ClusterServicesKubeControllerDeprecated>;
    readonly servicesKubeletDeprecated?: pulumi.Input<inputs.ClusterServicesKubeletDeprecated>;
    readonly servicesKubeProxyDeprecated?: pulumi.Input<inputs.ClusterServicesKubeProxyDeprecated>;
    readonly servicesKubeSchedulerDeprecated?: pulumi.Input<inputs.ClusterServicesKubeSchedulerDeprecated>;
    /**
     * SSH Agent Auth enable
     */
    readonly sshAgentAuth?: pulumi.Input<boolean>;
    /**
     * SSH Certificate Path
     */
    readonly sshCertPath?: pulumi.Input<string>;
    /**
     * SSH Private Key Path
     */
    readonly sshKeyPath?: pulumi.Input<string>;
    /**
     * RKE k8s cluster system images list
     */
    readonly systemImages?: pulumi.Input<inputs.ClusterSystemImages>;
    /**
     * Skip idempotent deployment of control and etcd plane
     */
    readonly updateOnly?: pulumi.Input<boolean>;
    /**
     * RKE k8s cluster upgrade strategy
     */
    readonly upgradeStrategy?: pulumi.Input<inputs.ClusterUpgradeStrategy>;
}
